{
 "title": "Regional performance analytic  - test",
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "region",
    "query": "{\"find\": \"terms\", \"field\": \"source.geo.country_iso_code.keyword\", \"size\": 500}"
   },
   { "name": "custom_region", "query": "*" },
   {
    "name": "inteval",
    "query": "1m,5m,10m,30m,1h,6h,8h,12h,1d,7d,14d,30d"
   },
   {
    "name": "env",
    "query": "{\"find\": \"terms\", \"field\": \"http.request.x_environment_id.keyword\", \"size\": 10}"
   },
   {
    "name": "ref_dm",
    "label": "Referer Domain ",
    "query": "{\"find\": \"terms\", \"field\": \"http.request.referer_domain.keyword\", \"size\": 1000, \"query\": \"source.geo.country_iso_code.keyword: $region\"}"
   },
   { "name": "filter" }
  ]
 },
 "panels": [
  { "title": "Open alert", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Open Alert Detail",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "metrics": [
      {
       "field": "select field",
       "id": "1",
       "meta": {},
       "settings": { "size": 500 },
       "type": "raw_data"
      }
     ],
     "query": "alert_state.keyword:open",
     "timeField": "timestamp"
    }
   ]
  },
  { "title": "$region status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 }, "repeat": "region" },
  {
   "title": "Total Request",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "$inteval", "min_doc_count": "1", "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "select field",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "source.geo.country_iso_code.keyword: $region AND  http.request.x_environment_id.keyword:custom",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Total orders",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 5, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "date", "id": "2", "settings": { "interval": "$inteval", "min_doc_count": "1", "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "_type:OrderItem AND country: $region",
     "timeField": "date"
    }
   ]
  },
  {
   "title": "Order count",
   "type": "graph",
   "gridPos": { "h": 6, "w": 14, "x": 10, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      { "field": "date", "id": "2", "settings": { "interval": "$inteval", "min_doc_count": "1", "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "_type:OrderItem AND country: $region",
     "timeField": "date"
    }
   ]
  },
  {
   "title": "Moving Avg.  request Latency",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "$inteval", "min_doc_count": "1", "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "http.response.time",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      },
      {
       "field": "1",
       "hide": true,
       "id": "3",
       "meta": {},
       "pipelineAgg": "1",
       "settings": {
        "minimize": false,
        "model": "simple",
        "window": 5
       },
       "type": "moving_avg"
      }
     ],
     "query": "source.geo.country_iso_code.keyword: $region AND http.request.x_environment_id:$env",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Seller dashboard Moving Avg. Latency",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "$inteval", "min_doc_count": "1", "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "http.response.time",
       "hide": true,
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      },
      {
       "field": "1",
       "id": "3",
       "meta": {},
       "pipelineAgg": "1",
       "settings": {
        "minimize": false,
        "model": "simple",
        "window": 5
       },
       "type": "moving_avg"
      }
     ],
     "query": "source.geo.country_iso_code.keyword: $region AND http.request.x_environment_id:$env AND http.request.referrer: \"https://dashboard.chipchip.com/manager/v2/\" AND http.request.referer_path.keyword: \"/manager/v2/\" AND url.original.keyword: \"/gateway/gql\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Http status",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "http.response.status_code",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_count", "size": "20" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "$inteval", "min_doc_count": "1", "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "source.geo.country_iso_code.keyword: $region AND http.request.x_environment_id:$env",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Route Latency",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "url.path.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_count", "size": "50" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "$inteval", "min_doc_count": "1", "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "http.response.time",
       "hide": true,
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      },
      {
       "field": "1",
       "id": "4",
       "meta": {},
       "pipelineAgg": "1",
       "settings": {
        "minimize": false,
        "model": "simple",
        "window": 5
       },
       "type": "moving_avg"
      }
     ],
     "query": "source.geo.country_iso_code.keyword: $region AND http.request.x_environment_id:$env",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Top hit referer path",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "http.request.referer_path.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "$inteval", "min_doc_count": "1", "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "http.response.time",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "source.geo.country_iso_code.keyword: $region AND http.request.x_environment_id:$env",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Top hit Route ",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "url.path.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "$inteval", "min_doc_count": "1", "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "http.response.time",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "source.geo.country_iso_code.keyword: $region AND http.request.x_environment_id:$env",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Top hit referer path latency",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "http.request.referer_path.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "$inteval", "min_doc_count": "1", "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "http.response.time",
       "hide": true,
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      },
      {
       "field": "1",
       "id": "4",
       "meta": {},
       "pipelineAgg": "1",
       "settings": {
        "minimize": false,
        "model": "simple",
        "window": 5
       },
       "type": "moving_avg"
      }
     ],
     "query": "source.geo.country_iso_code.keyword: $region AND http.request.x_environment_id:$env",
     "timeField": "@timestamp"
    },
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "$inteval", "min_doc_count": "1", "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "http.response.time",
       "hide": true,
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      },
      {
       "field": "1",
       "id": "4",
       "meta": {},
       "pipelineAgg": "1",
       "settings": {
        "minimize": false,
        "model": "simple",
        "window": 5
       },
       "type": "moving_avg"
      }
     ],
     "query": "source.geo.country_iso_code.keyword: $region AND http.request.x_environment_id:$env",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Top Source Address",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "source.address.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_count", "size": "20" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "$inteval", "min_doc_count": "1", "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "source.geo.country_iso_code.keyword: $region AND http.request.x_environment_id:$env",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Top referer domain",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "http.request.referer_domain.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_count", "size": "20" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "$inteval", "min_doc_count": "1", "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "source.geo.country_iso_code.keyword: $region AND http.request.x_environment_id:$env",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Top ASN",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 38 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "source.as.organization.name.keyword",
       "id": "4",
       "settings": { "min_doc_count": "1000", "order": "desc", "orderBy": "_count", "size": "50" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "source.as.number",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_count", "size": "20" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "$inteval", "min_doc_count": "1", "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "source.geo.country_iso_code.keyword: $region AND http.request.x_environment_id:$env",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "User-Agent",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 44 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "user_agent.name.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_count", "size": "20" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "$inteval", "min_doc_count": "1", "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "source.geo.country_iso_code.keyword: $region AND http.request.x_environment_id:$env",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Top Country",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 44 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "source.geo.country_iso_code.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_count", "size": "50" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "$inteval", "min_doc_count": "1", "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "source.geo.country_iso_code.keyword: $region AND http.request.x_environment_id:$env",
     "timeField": "@timestamp"
    }
   ]
  }
 ]
}