{
 "title": "SLO Dashboard",
 "tags": [
  "SRE",
  "SLI",
  "Observability"
 ],
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "Interval",
    "label": "Interval",
    "query": "1m,5m, 10m,30m,1h,6h,12h,1d,7d,14d"
   },
   {
    "name": "service",
    "query": "sl-dashboard, sl-email, sl-retail-production-bots, sl-retail-production-custom, sl-retail-production-teechip, fruit4k-old, sl-manager, sl-marketing, sl-analytics, sl-report, sl-rewards, sl-retail-user, sl-cash-rewards, sl-catalog, sl-gateway, sl-discounts, sl-seller-manager, sl-campaign, sl-stripe-issuing"
   }
  ]
 },
 "panels": [
  { "title": "Uptime", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Teechip Site Status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "summary.up",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "target: \"teechip_uptime\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Teechip Uptime",
   "type": "graph",
   "gridPos": { "h": 6, "w": 20, "x": 4, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "summary.up",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "target: \"teechip_uptime\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Teechip Uptime Availability",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expression": "(A['timeUp']/(A['timeUp'] + B['timeDown']))*100",
     "outputMetricName": "Uptime(%)",
     "periods": 7,
     "timeshiftUnit": "days"
    }
   ]
  },
  { "title": "Buyer Side", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Site Availability",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "$Interval", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "availability_rate.availability_rate",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "element.keyword:site_availability",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Site Latency",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "$Interval", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "latency.avg",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "element.keyword:site_latency AND NOT latency.avg:0",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Conversion Availability",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 8 },
   "repeat": "element",
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "$Interval", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "availability_rate.availability_rate",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "element.keyword:conversion_availability",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Conversion Latency",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "$Interval", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "latency.avg",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "element.keyword: conversion_latency AND NOT latency.avg:0",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Mockup Service Availability",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "$Interval", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "availability_rate.availability_rate",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "element.keyword: mockup_availability",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "OObilling Availability",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "$Interval", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "availability_rate.availability_rate",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "element.keyword: oobilling_availability",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Profit stats latency",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "$Interval", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "latency.avg",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "element.keyword: profit_stats_latency AND NOT latency.avg:0",
     "timeField": "timestamp"
    }
   ]
  },
  { "title": "Seller Side", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "\bCampaign Creation Availability",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "$Interval", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "availability_rate.availability_rate",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "element.keyword: campaign_creation_availability",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Seller Dashboard Latency",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "$Interval", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "latency.avg",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "element.keyword:seller_dashboard_latency AND NOT latency.avg:0",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Profit Stats Availability",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "$Interval", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "availability_rate.availability_rate",
       "id": "1",
       "meta": {},
       "settings": {
        "missing": null
       },
       "type": "avg"
      }
     ],
     "query": "element.keyword:profit_stats_availability",
     "timeField": "timestamp"
    }
   ]
  },
  { "title": "Other systems", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "TC Card availability",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "timestamp",
       "id": "2",
       "settings": { "interval": "$Interval", "min_doc_count": "1", "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "field": "availability_rate.availability_rate",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "element.keyword: tccard_availability",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "TC Card latency",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": "1", "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "latency.avg",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "element.keyword: tccard_latency AND NOT latency.avg:0",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Customer emails being failed",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "$Interval", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "value",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "element_type.keyword:sl-email-marketing-send AND status:failed",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "MicroServices",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 },
   "collapsed": true,
   "panels": [
    {
     "title": "$service status",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 35 },
     "repeat": "service",
     "yaxes": [
      { "format": "short", "label": "Site status" }
     ],
     "targets": [
      {
       "bucketAggs": [
        { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "summary.up",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "avg"
        }
       ],
       "query": "monitor.id:$service-uptime",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "$service status",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 35 },
     "yaxes": [
      { "format": "short", "label": "Site status" }
     ],
     "targets": [
      {
       "bucketAggs": [
        { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "summary.up",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "avg"
        }
       ],
       "query": "monitor.id:$service-uptime",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "$service status",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 35 },
     "yaxes": [
      { "format": "short", "label": "Site status" }
     ],
     "targets": [
      {
       "bucketAggs": [
        { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "summary.up",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "avg"
        }
       ],
       "query": "monitor.id:$service-uptime",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "$service status",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 35 },
     "yaxes": [
      { "format": "short", "label": "Site status" }
     ],
     "targets": [
      {
       "bucketAggs": [
        { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "summary.up",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "avg"
        }
       ],
       "query": "monitor.id:$service-uptime",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "$service status",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 42 },
     "yaxes": [
      { "format": "short", "label": "Site status" }
     ],
     "targets": [
      {
       "bucketAggs": [
        { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "summary.up",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "avg"
        }
       ],
       "query": "monitor.id:$service-uptime",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "$service status",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 42 },
     "yaxes": [
      { "format": "short", "label": "Site status" }
     ],
     "targets": [
      {
       "bucketAggs": [
        { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "summary.up",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "avg"
        }
       ],
       "query": "monitor.id:$service-uptime",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "$service status",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 42 },
     "yaxes": [
      { "format": "short", "label": "Site status" }
     ],
     "targets": [
      {
       "bucketAggs": [
        { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "summary.up",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "avg"
        }
       ],
       "query": "monitor.id:$service-uptime",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "$service status",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 42 },
     "yaxes": [
      { "format": "short", "label": "Site status" }
     ],
     "targets": [
      {
       "bucketAggs": [
        { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "summary.up",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "avg"
        }
       ],
       "query": "monitor.id:$service-uptime",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "$service status",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 49 },
     "yaxes": [
      { "format": "short", "label": "Site status" }
     ],
     "targets": [
      {
       "bucketAggs": [
        { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "summary.up",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "avg"
        }
       ],
       "query": "monitor.id:$service-uptime",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "$service status",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 49 },
     "yaxes": [
      { "format": "short", "label": "Site status" }
     ],
     "targets": [
      {
       "bucketAggs": [
        { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "summary.up",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "avg"
        }
       ],
       "query": "monitor.id:$service-uptime",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "$service status",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 49 },
     "yaxes": [
      { "format": "short", "label": "Site status" }
     ],
     "targets": [
      {
       "bucketAggs": [
        { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "summary.up",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "avg"
        }
       ],
       "query": "monitor.id:$service-uptime",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "$service status",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 49 },
     "yaxes": [
      { "format": "short", "label": "Site status" }
     ],
     "targets": [
      {
       "bucketAggs": [
        { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "summary.up",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "avg"
        }
       ],
       "query": "monitor.id:$service-uptime",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "$service status",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 56 },
     "yaxes": [
      { "format": "short", "label": "Site status" }
     ],
     "targets": [
      {
       "bucketAggs": [
        { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "summary.up",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "avg"
        }
       ],
       "query": "monitor.id:$service-uptime",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "$service status",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 56 },
     "yaxes": [
      { "format": "short", "label": "Site status" }
     ],
     "targets": [
      {
       "bucketAggs": [
        { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "summary.up",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "avg"
        }
       ],
       "query": "monitor.id:$service-uptime",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "$service status",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 56 },
     "yaxes": [
      { "format": "short", "label": "Site status" }
     ],
     "targets": [
      {
       "bucketAggs": [
        { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "summary.up",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "avg"
        }
       ],
       "query": "monitor.id:$service-uptime",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "$service status",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 56 },
     "yaxes": [
      { "format": "short", "label": "Site status" }
     ],
     "targets": [
      {
       "bucketAggs": [
        { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "summary.up",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "avg"
        }
       ],
       "query": "monitor.id:$service-uptime",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "$service status",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 63 },
     "yaxes": [
      { "format": "short", "label": "Site status" }
     ],
     "targets": [
      {
       "bucketAggs": [
        { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "summary.up",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "avg"
        }
       ],
       "query": "monitor.id:$service-uptime",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "$service status",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 63 },
     "yaxes": [
      { "format": "short", "label": "Site status" }
     ],
     "targets": [
      {
       "bucketAggs": [
        { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "summary.up",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "avg"
        }
       ],
       "query": "monitor.id:$service-uptime",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "$service status",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 63 },
     "yaxes": [
      { "format": "short", "label": "Site status" }
     ],
     "targets": [
      {
       "bucketAggs": [
        { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "summary.up",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "avg"
        }
       ],
       "query": "monitor.id:$service-uptime",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "$service status",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 63 },
     "yaxes": [
      { "format": "short", "label": "Site status" }
     ],
     "targets": [
      {
       "bucketAggs": [
        { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "summary.up",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "avg"
        }
       ],
       "query": "monitor.id:$service-uptime",
       "timeField": "@timestamp"
      }
     ]
    }
   ]
  }
 ]
}